### ISSUE TITLE
High-resolution scans used by Thomas Malten for digitization

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/SKD#14]
@funderburkjim / @thomasincambodia 

Could these SKD HR scans mentioned in the skd-meta2.txt be made accessible?

They would be helpful for error checking in the text.

**Comment by Andhrabharati** [comment]
1. The 3 MACRONs can safely be deleted, as they are extra characters wrt the print.

2. The × at `<L>13677` **हरि × काम्यः** could be replaced as **हरिᳲकाम्यः or हरिᳵकाम्यः** with a jihvAmUlIya character (ᳲ : \u1CF2 or ᳵ : \u1CF5); and at `<L>36451` **शूर × ष्यञ्** be replaced as **शूर + ष्यञ्** with a + character [as present everywhere else as `+ ष्यञ्`].

3. The „ at `<L>1861` to be replaced with a regular comma (typo); at `<L>16330` to be replaced with a “ (\u201C); at `<L>17510` to be replaced by a comma (print error).

4. The £ (24 places) to be replaced by ꣳ (\uA8F3) throughout.

5. The ¤ character is a special one, only to be seen in the private area of Siddhanta font! However it could be approximately rendered as ॱᳪ᳭ (\u0971 + \u1CEA + \u1CED).

6. And like in VCP, the SKD also has unmatched quote marks (‘ :1398 vs. ’ :1350 and “ :53134 vs. ” :52816) and could be resolved quickly.

**This finishes my looking against the meta2 data!**

**Comment by Andhrabharati** [comment]
@drdhaval2785,

like to do these corrections?

**Comment by drdhaval2785** [comment]
I would be able to do these tomorrow.

**Comment by funderburkjim** [comment]
Have found email from Thomas from 2017 on this subject, and have mentioned this request to him.

**Comment by thomasincambodia** [comment]
here is the link:

https://u.pcloud.link/publink/show?code=kZLwTVVZeyLDHmEoS6j1u8fj3ujz1FS1vRcV

**Comment by gasyoun** [comment]
> https://u.pcloud.link/publink/show?code=kZLwTVVZeyLDHmEoS6j1u8fj3ujz1FS1vRcV

23 GB scan - now this is a big file I call ))

**Comment by thomasincambodia** [comment]
@gasyoun 
it's not a single file, but each page in a  jpeg file, size ca. 8 MB

**Comment by Andhrabharati** [comment]
These scans definitely helped the typists doing a good job with this work.

I have another source (Rastriya Sanskrita Samsthan, New Delhi), that was independently done and brought out as a digital CD version and is better at many places (though poor at some places) wrt Cologne text; a MELD comparison (as initiated for VCP, with Tirupati  & Cologne versions) would definitely be a job worthwhile.
[I also have the physical copies of RSS edition volumes, which are far better than the Chowkhamba edition volumes.]

@thomasincambodia,
could you pl. give the HR scans of Sabdakalpadruma front pages as well?

**Comment by Andhrabharati** [comment]
I had shared the CD original content with Marcis few months back, when he wanted to try extracting the text; do not know if any attempt was made at his end or about its outcome.

**Comment by drdhaval2785** [comment]
Points 1-5 https://github.com/sanskrit-lexicon/SKD/issues/14#issuecomment-1066089770 done.
Point 6 remaining.

**Comment by Andhrabharati** [comment]
> here is the link:
> 
> https://u.pcloud.link/publink/show?code=kZLwTVVZeyLDHmEoS6j1u8fj3ujz1FS1vRcV

@thomasincambodia 
The page skd1_283 is cut at the bottom, and the pages skd2_257, skd2_402, skd2_414, skd2_415 are missing altogether.

Could you pl. check these once in you data and update?

**Comment by thomasincambodia** [comment]
> @thomasincambodia, could you pl. give the HR scans of Sabdakalpadruma front pages as well?
@Andhrabharati 
these were not scanned.

**Comment by thomasincambodia** [comment]
> @thomasincambodia The page skd1_283 is cut at the bottom; the 7 pages skd2_280, skd3_437, skd3_648, skd3_695, skd4_017, skd4_177, skd4_465 are empty (zero bytes) and the 4 pages skd2_257, skd2_402, skd2_414, skd2_415 are missing altogether.
> 
> Could you pl. check these once in you data and update?

uploaded

**Comment by Andhrabharati** [comment]
> 

@thomasincambodia, uploaded at the same link as earlier?

I see the above pages' status (at this link) to be the same (cut, zero size and missing) still.

**Comment by Andhrabharati** [comment]
> https://u.pcloud.link/publink/show?code=kZqhG0VZ9AAXBwCk4K0cR3PVpaLCqVb22zwX
> 
> hope this will work now
> 

@thomasincambodia 
This link has SabdasAgara, not the Sabdakalpadruma!
**And of course, I will take it as well.**

BTW, are there any other HR scans that you would like to share?
`---------------------------------`

> files skd1_317 to 331 contain preface material pages {in reverse order)

Yes, seen that the front pages' last portion is at the end the SKD1 scans.
[Another 14 pages in the beginning are not in the scan.]

**Comment by gasyoun** [comment]
> BTW, are there any other HR scans that you would like to share?

Seems there is more than just Sabdakalpadruma

**Comment by thomasincambodia** [comment]
> > https://u.pcloud.link/publink/show?code=kZqhG0VZ9AAXBwCk4K0cR3PVpaLCqVb22zwX
> > hope this will work now
> 
> @thomasincambodia This link has SabdasAgara, not the Sabdakalpadruma! **And of course, I will take it as well.**
> 
> BTW, are there any other HR scans that you would like to share? `---------------------------------`
> 
> > files skd1_317 to 331 contain preface material pages {in reverse order)
> 
> Yes, seen that the front pages' last portion is at the end the SKD1 scans. [Another 14 pages in the beginning are not in the scan.]

new link with the missing parts of SKD (except for the English title an preface):

https://u.pcloud.link/publink/show?code=kZ0rb5VZCTml6uugwSbt5UXvYRroB8cCLF2X

----

> @thomasincambodia This link has SabdasAgara, not the Sabdakalpadruma! **And of course, I will take it as well.**

you are welcome! (in case you use any of the Cologne materials for your publications an acknowledgment to www.sanskrit-lexicon.uni-koeln.de will always be appreciated.)

----
> > BTW, are there any other HR scans that you would like to share?
> 
> Seems there is more than just Sabdakalpadruma

I will try to find out. (sorry for the late reply)

**Comment by Andhrabharati** [comment]
> new link with the missing parts of SKD (except for the English title an preface):
> 
> https://u.pcloud.link/publink/show?code=kZ0rb5VZCTml6uugwSbt5UXvYRroB8cCLF2X

Thank you for filling the SKD gaps, @thomasincambodia.

> you are welcome! (in case you use any of the Cologne materials for your publications an acknowledgment to [www.sanskrit-lexicon.uni-koeln.de](http://www.sanskrit-lexicon.uni-koeln.de) will always be appreciated.)

No, I am not into any publishing (so far!); I would just be using these for going through (proofing etc.) the Cologne works themselves.
And I agree that an acknowledgement is **always to be given** if the Cologne texts are used somewhere else.

**Comment by Andhrabharati** [comment]
> > new link with the missing parts of SKD (except for the English title an preface):
> > https://u.pcloud.link/publink/show?code=kZ0rb5VZCTml6uugwSbt5UXvYRroB8cCLF2X
> 
> Thank you for filling the SKD gaps, @thomasincambodia.

Seen that the 7 'zero byte' pages are yet to be filled up, @thomasincambodia 

> The page skd1_283 is cut at the bottom; the 7 pages skd2_280, skd3_437, skd3_648, skd3_695, skd4_017, skd4_177, skd4_465 are empty (zero bytes) and the 4 pages skd2_257, skd2_402, skd2_414, skd2_415 are missing altogether.

**Comment by thomasincambodia** [comment]
![skd1_283](https://user-images.githubusercontent.com/15843889/161171705-62c1e755-7551-4683-88a8-a5d7174f9c1b.jpg)

this is my download of page skd1_283.jpg via link
https://u.pcloud.link/publink/show?code=kZ0rb5VZCTml6uugwSbt5UXvYRroB8cCLF2X
which doesn't seem to be cut.

I also find the four pages in skd2 you report as missing.

I will check for the other seven pages and upload them if necessary.

**Comment by thomasincambodia** [comment]
@Andhrabharati 
https://u.pcloud.link/publink/show?code=kZ0rb5VZCTml6uugwSbt5UXvYRroB8cCLF2X

please check if everything is complete now at your end.

-----

@funderburkjim 
please check your mail.

**Comment by Andhrabharati** [comment]
Thank you @thomasincambodia, now I have all the scanned pages in tact at my end also.

Any specific reason for your giving 3_473 again (though not in my list as required)?
Also the pages 1_317 to 1_332 are there in the initial link itself, though you had given them again in the next batches too!

**Comment by thomasincambodia** [comment]
@Andhrabharati 
just ignore them

**Comment by Andhrabharati** [comment]
@funderburkjim 

You may consider replacing the present cdsl scan pages with these HR scans from Thomas.

Though the individual jpg files are of large size, the pdf pages can be made smaller (to the tune of 25-30 times less), without losing the clarity.

This would help any interested people (are there any!!?) to benefit from these good scans of SKD.

**Comment by Andhrabharati** [comment]
And, so is the case with SHS HR scans given here by Thomas.

**Comment by Andhrabharati** [comment]
Unless Jim would like to replace [the SHS scans](https://github.com/sanskrit-lexicon/SKD/issues/14#issuecomment-1086780108), this issue may be closed now.

The [remaining point](https://github.com/sanskrit-lexicon/SKD/issues/14#issuecomment-1066426693) in my post that is left by Dhaval shall be handled in my present exercise.

**Comment by Andhrabharati** [comment]
@gasyoun might be interested in seeing these original title pages of SKD Devanagari edition--

**SKD-1 1886**

![SKD-1 1886](https://github.com/sanskrit-lexicon/SKD/assets/75209130/9df2ce46-3635-460d-849a-043a2b8fb4d4)

**SKD-2 1889**

![SKD-2 1889](https://github.com/sanskrit-lexicon/SKD/assets/75209130/c67a5f62-9ec3-4cab-99e6-b64cf00f3a75)

**SKD-3 1887**

![SKD-3 1887](https://github.com/sanskrit-lexicon/SKD/assets/75209130/228d8817-9e9a-4239-a83a-7dd68f3706f3)

**SKD-4 1892**

![SKD-4 1892](https://github.com/sanskrit-lexicon/SKD/assets/75209130/88727912-caee-4075-b464-08ca91b06389)

**SKD-5 1894**

![SKD-5 1894](https://github.com/sanskrit-lexicon/SKD/assets/75209130/a6bdb5b7-2c0a-4414-b2e6-fe8353bcd88c)

Interesting to note that Vol.2 got published after Vol.3 (2 years later), could it be because the volume size is quite bigger (nearly double!)?

**Comment by Andhrabharati** [comment]
**Some statistics:**

Out of the ~40k substantives of SKD,

- just 60 (sixty) entries have no "lingAnuSAsana" (gender info); probably these could be filled with the help from other dictionaries. [**These are in addition to the 51 alphabet entries.**]
[entries without gender info.txt](https://github.com/sanskrit-lexicon/SKD/files/13259999/entries.without.gender.info.txt)

- 90% have the word derivation ("vyutpatti") at the beginning of the entry itself; and noted that very few have this "info" inside the entry. [**It is estimated that about 9-10% are without vyutpatti info, on the whole.**]

**Comment by Andhrabharati** [comment]
Noticed, by chance, two entry words that were merged into the previous entry in the CDSL text.

**This prompts me to look for all such entries, to be the next point in my SKD work.**

**Comment by funderburkjim** [comment]
> Unless Jim would like to replace shs.scans ...

@Andhrabharati  SHS =  'Shabda-Sagara Sanskrit-English Dictionary'.  I  think there is no need for higher resolution scans for SHS at the present time.  

Accordingly, closing this issue.
