### ISSUE TITLE
ड्२अ > ड़

### ISSUE THREAD

**Issue by Shalu411** [sanskrit-lexicon/SKD#4]
Namaste
Instead of ड्२अ - for the letter D with a dot below, could you please use that letter directly?
It is there in Mangal font- ड़ 
I do not know why this letter is given so complicated way, what issues there in it. Its difficult to make it out in first instance, without seeing scan.
Thanks

**Comment by drdhaval2785** [comment]
I think down the line @funderburkjim got the courage to remove the nuktas from skd.txt too. Can you give a background to it Jim?
There is no d2 in the skd.txt now.
