### ISSUE TITLE
Year 1822 -> 1886 or 1886-1891

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/SKD#5]
Are you sure about the year on homepage?
SKD 1822    Sabda-kalpadruma    B   L   A   M   D  
All I can find is a <a href="https://www.worldcat.org/search?q=Ra%CC%84ja%CC%84+Ra%CC%84dha%CC%84ka%CC%84ntadeva&dblist=638&fq=yr%3A1886&qt=facet_yr%3A">bit</a> younger.
RĀDHĀKĀNTADEVA. (1886). Śabdakalpadrumaḥ.

**Comment by drdhaval2785** [comment]
@gasyoun any reason for invalid label?

**Comment by gasyoun** [comment]
> reason for invalid label?

No clue.

**Comment by funderburkjim** [comment]
There is a review of skd  in the front matter that is dated 1835:
https://www.sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/_images/skd_Page_13_Image_0002.png

So, 1822 seems possible, although the version we are using appears to be dated 1888:

https://www.sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/dictionaries/prefaces/skdpref/skdpref04.html

I've posed this question to Thomas and Peter,

**Comment by gasyoun** [comment]
> I've posed this question to Thomas and Peter

Thanks.

**Comment by funderburkjim** [comment]
Peter replies:
```
	In the header for the Sanskrit Library, I have the following:
      <edition>expanded edition</edition>
      <imprint>
       <pubPlace>Calcutta</pubPlace>
       <publisher>Baptist Mission Press</publisher>
       <date>1886</date>
      </imprint>

and

      <edition>third edition, reprint of the 1886 edition</edition>
      <imprint>
       <pubPlace>Varanasi</pubPlace>
       <publisher>Chowkhamba Sanskrit Series Office</publisher>
       <date>1967</date>

The original was published in fascicules over a couple of decades.  The link to Harvard’s catalogue record is:

https://hollis.harvard.edu/primo-explore/fulldisplay?docid=01HVD_ALMA211874927840003941&context=L&vid=HVD2&lang=en_US&search_scope=everything&adaptor=Local Search Engine&tab=everything&query=any,contains,Sabdakalpadruma&offset=0

where it says:

Published
Kalikātā Nagarē : Biśvanātha Debarāma, 1743-1773 [1821-1851]

In Sanskrit; Bengali script.

The author: Rādhākāntadeva, 1784-1867


```

**Comment by funderburkjim** [comment]
Either 1886 (Worldcat  and Peter's Sanskritlibrary entrance)

or 1888 From the 'Front matter'

Interesting that both of these dates may be after the Author's lifetime.

I like 1886 .

@gasyoun   Do you concur with using 1886?

**Comment by gasyoun** [comment]
> Do you concur with using 1886?

Not yet. https://groups.google.com/g/bvparishat/c/LXcBm9BI1gM

**Comment by gasyoun** [comment]
> Do you concur with using 1886?

Yes.

```
The Sabdakalpadruma was originally published by Radhakanta Deb as 8 volumes, in Bengali script, during 1822-1857.
```

and

```
The current edition being used and quoted widely is the revised ("considerably improved, carefully revised and published") edition by Varadaprasada Basu & Durgacharana Basu as 5 volumes (1st Vol. in Saka 1808 and 5th vol. in Saka 1813, i.e. about A.D. 1886-1891), in "Nagari letters".
```

**Comment by funderburkjim** [comment]
Change to 1886 made on homepage.

Also changed tab title in displays to 1886 for skd.

**Comment by gasyoun** [comment]
> Change to 1886 made on homepage.

Thanks.
