### ISSUE TITLE
Correction in purANa

### ISSUE THREAD

**Issue by chandrasekharanr** [sanskrit-lexicon/SKD#7]
Submitting a correction request here because the explanation may not fit the textbox there.

The entry purANaM in the dictionary shows as 

पुराणं , क्ली, (पुरा भवमिति । पुरा + “सायं-
चिरंप्राह्णेप्रगेऽव्ययेभ्य**ष्ट्युट्युलौ** तुट् च ।” ४ । ३ ।
२३ । इति **_ट्युः_** । “पूर्ब्बकालैकसर्व्वजरत्पुराणनव-
केवलाः समानाधिकरणेन ।” २ । १ । ४९ । इति
निपातनात् तुडभावः ।

This is correct.

While the next entry purANaH shows --

पुराणः , पुं, (पुरा पुर्ब्बस्मिन् काले भव इति ।
पुरा + “सायंचिरंप्राह्णेप्रगेऽव्ययेभ्य**ष्ट्युष्ट्युलौ**
तुट्च ।” ४ । ३ । २३ । इति **_ष्ट्युः_** निपातनात्
तुडभावः ।)

This is an error. The text in bold should exactly match!

This error is propagated to the word पुरातनः (Cologne record ID=21934/21935) also.

Looks like this error was made in the printed text itself! It is clearly not an error from the author as he got it right in the first entry above, and then the error crept in to subsequent entries.

Can this be fixed?

**Comment by gasyoun** [comment]
> Can this be fixed?

Sure. What exactly needs to be replaced by what?

**Comment by chandrasekharanr** [comment]
> Sure. What exactly needs to be replaced by what?

I have mentioned this in my original message :  _The text in bold should exactly match!_

Also, 

पुरा + ष्ट्युस्तुट्  should be changed to पुरा + ट्युस्तुट् in Cologne record ID=21934
इति ष्ट्युस्तुट् च should be changed to इति ट्युस्तुट् च  in Cologne record ID=21935

**Comment by funderburkjim** [comment]
Here are corrections I plan to submit (not yet submitted):  These use the slp1 spellings of the digitization skd.txt.
```
; L= 21931 purARaH
270149 old <>purA + “sAyaMciraMprAhReprage'vyayeByazwyuzwyulO
270149 new <>purA + “sAyaMciraMprAhReprage'vyayeByazwyuwyulO
270150 old <>tuwca .” 4 . 3 . 23 . iti zwyuH nipAtanAt
270150 new <>tuwca .” 4 . 3 . 23 . iti wyuH nipAtanAt
; L= 21934 purAtanaH
270179 old purAtanaH¦, puM, (purA BavaH . purA + zwyustuw ca .)
270179 new purAtanaH¦, puM, (purA BavaH . purA + wyustuw ca .)
; L= 21935 purAtanaH
270190 old <>+ “sAyaMcireti .” 4 . 3 . 23 . iti zwyustuw
270190 new <>+ “sAyaMcireti .” 4 . 3 . 23 . iti wyustuw
```

@chandrasekharanr  Please confirm

**Comment by chandrasekharanr** [comment]
Yes, this is correct.

**Comment by funderburkjim** [comment]
This Sanskrit is too hard for me to understand properly.

First of all, what is the grammatical form 'wyuH' ?  and what is the grammatical form 'wyustuw' ?

**Comment by chandrasekharanr** [comment]
The wyuH is an affix which comes and attaches to the stem purA to generate the word purAtanAH. The word purA is an indeclinable.

The wyustuw is actually wyuH + tuw. The sandhi has made it wyustuw 

Here is an English commentary to the sutra 4.3.23 --

After the words 1. सायं 'at eve' 2. चिरम् 'for a long time' 3. प्राह्णे 'in the forenoon' 4. प्रगे 'at dawn' and after indeclinables expressing time, there are the affixes **ट्यु** and ट्युल् and their augment is तुट्।
(https://ashtadhyayi.github.io/sutra-details/?sutra=4.3.23)

**Comment by funderburkjim** [comment]
Thanks for the mini-lesson!  

I'll get the corrections installed.

**Comment by funderburkjim** [comment]
Corrections installed.
